### ISSUE TITLE
Error when I try to import @rinminase/ng-charts

### ISSUE THREAD

**Issue by vladprundurel** [RinMinase/ng-charts#1]
Hello! I'm using Angular 9 and receive this error when I try to import this library. Can you please help me?

Also, the link for Pie Chart that you recommend is: [Pie Chart](https://stackblitz.com/edit/ng2-charts-pie-template?file=src%2Fapp%2Fapp.component.ts) that imports chart.js in his project for setting ChartType and ChartOptions. Should I import chart.js as well? Thanks

**

> ERROR in node_modules/@rinminase/ng-charts/lib/charts.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
> 
> This likely means that the library (@rinminase/ng-charts) which declares ChartsModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**

**Comment by RinMinase** [comment]
Hey vladprundurel!

I’ll be looking into the issue you have created right away. I’ll notify you using the issue ticket or by email.

Likewise, thank you very much for also taking the time to look into the root of this problem.

Regards,
Kristian Alunan

From: vladprundurel
Sent: Friday, May 8, 2020 22:22
To: RinMinase/ng-charts
Cc: Subscribed
Subject: [RinMinase/ng-charts] Error when I try to import @rinminase/ng-charts(#1)

Hello! I'm using Angular 9 and receive this error when I try to import this library. Can you please help me?
ERROR in node_modules/@rinminase/ng-charts/lib/charts.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
This likely means that the library (@rinminase/ng-charts) which declares ChartsModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by RinMinase** [comment]
Hey @vladprundurel! May I know the version of both `Angular 9` and the `@rinminase/ng-charts` you are using?

**Comment by RinMinase** [comment]
Hey @vladprundurel, I have updated the example codes in the readme file. Have a look at it sometime. Cheers! 😁

**Comment by RinMinase** [comment]
This is now the [Pie Chart example](https://stackblitz.com/edit/ng-charts-pie).

As for your question:

>Also, the link for Pie Chart that you recommend is: Pie Chart that imports chart.js in his project for setting ChartType and ChartOptions. Should I import chart.js as well?

The new examples in readme have removed those from the import statements. So, you don't need to add or import both the `ChartType` and `ChartOptions` from `chart.js`.

As for this:

>ERROR in node_modules/@rinminase/ng-charts/lib/charts.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

I could not replicate this in using `Angular 9.1.6` and `@rinminase/ng-charts 1.5.10`. May I know what versions are you using for your setup? If it's possible, can you create a minimal [live example](https://stackblitz.com/fork/angular-ivy) to replicate the problem in your setup?
