### ISSUE TITLE
Ionic - no chart rendered

### ISSUE THREAD

**Issue by akshatdevp** [RinMinase/ng-charts#10]
## Expected Behavior
A radar chart to be rendered

## Current Behavior
Blank space 

## Steps to Reproduce
1. Init an ionic project
2. add the sample radar as a new component
3.  add path from app-routing module to render the radar component 

## Possible Reasons and Suggestions
Something to do with ionic?

**Comment by RinMinase** [comment]
Unfortunately I am not not that quite familiar with Ionic, ☹

If it's possible, you can create a pull request for a fix for this one. 🤔
