### ISSUE TITLE
MomentJS - Deprecating warning

### ISSUE THREAD

**Issue by MDzyga** [RinMinase/ng-charts#2]
Hi,
MomentJS package depreacted one of methods and I get a warning in browser.

## Expected Behavior
Please fix it - change creating proper date using moment package.

## Current Behavior
`Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.`

## Steps to Reproduce

1. Add chart with type datetime

## Possible Reasons and Suggestions
Momentjs deprecated one of method

**Comment by RinMinase** [comment]
Alright. I'll have a look at it. 😁

**Comment by RinMinase** [comment]
@MDzyga can you please provide a replication using any online editors such as [stackblitz](https://stackblitz.com). I can't seem to replicate it with my setup here. Could you also provide the moment version you are using?

**Comment by MDzyga** [comment]
@RinMinase 
I figured it out, sorry for creating an issue.
I used DatePipe to transform date to format 'MMM YYYY'
