### ISSUE TITLE
Possible to define text inside doughnut chart

### ISSUE THREAD

**Issue by MDzyga** [RinMinase/ng-charts#4]
Hi,
I know it's a feature but I need to display some text (two lines) in the middle of doughnut chart.
I know I can set position absolute and next try to set proper left position but I need to support different resolutions.
Currently I have a problem between 1200px and 1370px

![image](https://user-images.githubusercontent.com/38663990/87665757-ba565380-c767-11ea-89ba-028e44b65cdd.png)

![image](https://user-images.githubusercontent.com/38663990/87665901-f7bae100-c767-11ea-9bff-2937838830f2.png)

**Comment by MDzyga** [comment]
I think I have to use plugin beforeDraw but I don't  know how to register custom plugin in config instead of directive

**Comment by RinMinase** [comment]
Hello @MDzyga,
I have no idea on how to implement this on the default ChartJS.

But as you said, you can use a plugin for this. Perhaps trying to use percents instead of pixels? Sadly, I'm not really sure on how to do this. 🤔

**Comment by MDzyga** [comment]
Hi @RinMinase,
I found this question on stackoverflow:
https://stackoverflow.com/questions/20966817/how-to-add-text-inside-the-doughnut-chart-using-chart-js
Probably it will fix my problem :)

**Comment by RinMinase** [comment]
Oohhhh nice! Hopefully it would. 👍🏻
I'll be closing this issue, as you already have found a possible fix to this problem.

Feel free to re-open it if you still have issues with it. 😁
Happy coding!

**Comment by MDzyga** [comment]
this is my solution :) 
```
this.plugins.push({
      id: 'centerText',
      beforeDraw: (chart: Chart) => {
        if (chart && text) {
          const textX: number = Math.round((chart.width - chart['legend'].width) / 2);
          const textY: number = (chart.height / 2) - 10;

          // title
          chart.ctx.font = `bold 18px Poppins`;
          chart.ctx.textAlign = 'center';
          chart.ctx.fillText(text.title, textX, textY);
          // subtitle
          chart.ctx.font = `16px Poppins`;
          chart.ctx.textAlign = 'center';
          chart.ctx.fillText(text.subtitle, textX, textY + 20);
        }
      },
    });
```

**Comment by RinMinase** [comment]
Woah! Nicely done. 👍🏻
