### ISSUE TITLE
ThemeService error reported in console

### ISSUE THREAD

**Issue by jegjessing** [RinMinase/ng-charts#5]
Two problems:

- Label and Color is not part of ng-charts, its named ChartColor and ChartLabel.
- ERROR NullInjectorError: StaticInjectorError(AppModule)[BaseChartDirective -> ThemeService]: 
StaticInjectorError(Platform: core)[BaseChartDirective -> ThemeService]: NullInjectorError: No provider for ThemeService!
in chrome console.

I followed your line example

**Comment by jegjessing** [comment]
Fixed by adding

  providers: [
    ThemeService
  ]

To the modules module.ts

Maybe an idea updating the documentation with these informations

**Comment by RinMinase** [comment]
@jegjessing, Hello 👋🏻
May I ask if this question has been fixed?

**Comment by jegjessing** [comment]
Hi,

Yes by following the example in the code and not the docs.
I would suggest updating the StackBlitz example

*Med venlig hilsen / Best regards*
Jarl Gjessing
Mobil: +45 60 72 17 16
Adresse: Klintevej 7, DK-3600 Frederikssund

**Comment by RinMinase** [comment]
I can't seem to replicate this using the existing StackBlitz Examples in the readme. 🤔
May you be able to create a live example (stackblitz or others) for replication.

**Comment by RinMinase** [comment]
I couldn't replicate this issue in the latest build.
Please try the reinstalling the latest one. 🙇🏻‍♂️
