### ISSUE TITLE
Doesn't show tooltips in last version

### ISSUE THREAD

**Issue by pblo666** [RinMinase/ng-charts#6]
public chartColor: DatasetColor[] = [
    {
      backgroundColor: 'rgba(0,0,0,0)',
      borderColor: '#2196f3',
      borderWidth: 1,
      pointBorderColor: 'orange',
      hoverBackgroundColor: 'green'
    },
  ];

  public chartType: ChartType = 'line';
  public options: ChartOptions = {
    
    responsive: true,
    legend: {
      display: false,
    },
    tooltips: {
      bodyFontColor: 'black',
      callbacks: {
        label: function (tooltipItem) {
          debugger;
          return '$' + Number(tooltipItem.yLabel) + ' and so worth it !';
        },
      },
      enabled: true,
      
    },
    scales: {
      xAxes: [
        {
          display: false,
        },
      ],
    },
  };

**Comment by RinMinase** [comment]
Hello @Vitaly1025. 👋🏻

May I know the version of both angular and the this library's version you are using? 🤔

I tried to replicate it using the latest version of angular (`v12.0.5`), 
with the latest version of this library (`v4.0.3`) and I could not replicate it.

[https://stackblitz.com/edit/ng-charts-line-zvusx7](https://stackblitz.com/edit/ng-charts-line-zvusx7)

**Comment by RinMinase** [comment]
As presented above tooltips for the latest version is working. 
I'll close this, as this issue seems to be invalid.

Feel free to re-open this again if the problem still arises. 😁
