### ISSUE TITLE
Error @rinminase/ng-charts ɵɵFactoryDeclaration

### ISSUE THREAD

**Issue by JPSantistebanQ** [RinMinase/ng-charts#7]
## Version
"@rinminase/ng-charts": "^4.2.1",

## Expected Behavior
Not error

## Current Behavior
import * as i0 from "@angular/core";
import * as i1 from "./base-chart.directive";
export declare class ChartsModule {
    static ɵfac: i0.ɵɵFactoryDeclaration<ChartsModule, never>;
    static ɵmod: i0.ɵɵNgModuleDeclaration<ChartsModule, [typeof i1.BaseChartDirective], never, [typeof i1.BaseChartDirective]>;
    static ɵinj: i0.ɵɵInjectorDeclaration<ChartsModule>;
}

## Steps to Reproduce
1. ng serve

## Possible Reasons and Suggestions
-

## Log error
 static ɵprov: i0.ɵɵInjectableDeclaration<ThemeService>;

**Comment by RinMinase** [comment]
Hello @JPSantistebanQ. 👋🏻
May you please upload a reproduction steps with a simple code in it showing the issue?

I could not seem to reproduce it on my end.

**Comment by RinMinase** [comment]
Closing this ticket due to inactivity.
