### ISSUE TITLE
ChartsModule cannot be imported

### ISSUE THREAD

**Issue by sasmitBiceps** [RinMinase/ng-charts#9]
I am trying to use this library for angular version 13.2.0.
When I try to import ChartsModule from your framework, it gives an error but NgChartsModule works. Can you please create a stackbliz example using this NgChartsModule? I am suing chartjs v3.5+

**Comment by RinMinase** [comment]
Hello @sasmitBiceps, 👋🏻
Did you try to use the beta version? Since the stable release version uses ChartJS v2.9, not v3.5.

**Comment by RinMinase** [comment]
I'll be closing this issue due to user inactivity. Thank you.
Feel free to reopen it if the issue still arises.
